### ISSUE TITLE
Long compution time for irregular solver

### ISSUE THREAD

**Issue by BuergerPascal** [fontanf/packingsolver#107]
Hi, 

First of all, a really useful project. I'm currently testing the Irregular Solver with 100 slightly different polygons. I plan to run it in parallel later, which is why I use the not-anytime-sequential mode. With both knapsack and binpacking with leftovers I don't get a complete solution. If I deactivate not-anytime-sequential in knapsack it creates a solution in 120 seconds with 100 parts. There is enough space in the bin for all the parts. It should be pretty quick to place everyone. I always calculate the area in advance and never fill more than 75%. Are there options to speed up the solver? Or is it the nature of the solver to find the best possible solution, are there ways to get a good enough solution. I'm attaching my file. Thanks in advance for your help. I'm looking forward to hearing from you.

[test.json](https://github.com/user-attachments/files/17734316/test.json)

        ./packingsolver_irregular \
        --verbosity-level 1 \
        --input ./test.json \
        --time-limit 120 \
        --optimization-mode not-anytime-sequential \
        --certificate solution_irregular.json \

**Comment by fontanf** [comment]
Hi,

"Bin packing with leftovers" really means that the remaining space on the bin must be optimized. Conceptually, if you're only interested in the number of bins, the "bin packing" or "knapsack" objectives are more suited.

But currently, even with the bin packing or knapsack objectives, the solver won't detect that the items should fit easily in the bin and use cheaper routines to find the packing.

First, if some items are identical, use the "copies" attribute instead of adding the same item multiple times. That will speed up the algorithm.

Then, the algorithm relies on a decomposition of the item shapes into trapezoids. The running time of the algorithm heavily depends on the number of trapezoids after the decomposition. Your items have a lot of vertices that lead to a decomposition into many trapezoids. The solver has a routine to allow some approximations in the decomposition if that makes it possible to reduce the number of trapezoids. Currently, this routine is rather conservative to avoid missing optimal solutions on small problems. That's not something easy to configure to make it work well in general. For now, you can try to tweak it manually in the code.

Commenting these 4 lines reduces the time to the first solution to 30s:
https://github.com/fontanf/packingsolver/blob/a2a34b087e1153fb64908a8a1e199cd8b756470d/src/irregular/polygon_simplification.cpp#L381

And then changing the value of the parameter to 0.1 reduces it to 4s:
https://github.com/fontanf/packingsolver/blob/a2a34b087e1153fb64908a8a1e199cd8b756470d/src/irregular/polygon_simplification.cpp#L348

You can also outer-approximate your shapes yourself before sending them to the solver.

I hope this helps.

**Comment by BuergerPascal** [comment]
Hi,

Thanks for your advice. Now it works for me. I simplified the polygons a bit beforehand and adjusted the lines in the source code according to your advice. It now works as I imagined. It now only takes a few seconds for a solution that is good enough for me. However, the not-anytime-sequential option cannot be used for me. The process here takes too long. A useful option here would be if I could define the number of cpus per solver. I will experiment with the number of cpus available. I tried num packing solvers = num cpus / 2. That works for me right now. Great job. I am continuing to follow the project and am excited about further improvements and documentation. It would be useful for me if I could define the id of the objects in the input so that I can find them straight away and don't have to assign them again. But that is another topic.

Cheers

**Comment by fontanf** [comment]
Great.

In "not-anytime" modes, you may need to adjust the `not_anytime_*` parameters to your needs:
https://github.com/fontanf/packingsolver/blob/a2a34b087e1153fb64908a8a1e199cd8b756470d/include/packingsolver/irregular/optimize.hpp#L64

These parameters can be changed from the command line:
https://github.com/fontanf/packingsolver/blob/a2a34b087e1153fb64908a8a1e199cd8b756470d/src/irregular/main.cpp#L80

>  It would be useful for me if I could define the id of the objects in the input so that I can find them straight away and don't have to assign them again.

That will probably come at some point. It's indeed easier to debug.

**Comment by bbeaulant** [comment]
> That will probably come at some point. It's indeed easier to debug.

Good news, Florian ;)

**Comment by BuergerPascal** [comment]
Hi,

thanks for the information. I am very satisfied with the performance. I have now carried out some tests with a very large variation of shapes. So far everything has worked. Thanks again and fantastic work.

Cheers

**Comment by fontanf** [comment]
Great. I close the issue.

Do not hesitate if you have other questions; and do not hesitate to send me a set of instances representative of the ones you solve if you can, so I can use them to evaluate future developments, for improvements and to avoid regressions.
