### ISSUE TITLE
RectangularGuillotine : Missing `first_cut_orientation` property in Solution 'append' method

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#116]
Hello,

In RectangleGuillotine solution `append` method, the newly created `SolutionBin` doesn't copy the `first_cut_orientation` property.

https://github.com/fontanf/packingsolver/blob/0600c9a82ccc74cf1ef592c0f3237cb1ec8f0d14/src/rectangleguillotine/solution.cpp#L98

Maybe adding the following line (at line 99) ?

```cpp
bin.first_cut_orientation = solution.bins_[bin_pos].first_cut_orientation;
```

Else, this method retrieve `bin` in two different ways : `solution.bin(bin_pos)` and `solution.bins_[bin_pos]`. Which one is the best to use ?

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

It's fixed in 9bc79da6daa638888674f359a51cc6d78f1ddbb1

`solution.bin(bin_pos)` is a public method that returns a **const** reference. `solution.bins_[bin_pos]` is private, it will only work inside the `Solution` class, but it can be modified. I would favor using `solution.bin(bin_pos)` when both are possible to emphasize that it won't be modified.
